@startuml
scale max 1920*1080
class BehaviorStrategy #2fadff/fafad2 {
}

World <-- BehaviorStrategy
SteeringBehaviors <-- BehaviorStrategy

class BodySystem #2fadff/fafad2 {
}


class Configs #adff2f/fafad2 {
}


class DataProviderSystem #2fadff/fafad2 {
}

World <-- DataProviderSystem

class Environment #2fadff/fafad2 {
}

World <-- Environment

class World #2fadff/fafad2 {
}


class Helpers #adff2f/fafad2 {
}


class InputSystem #2fadff/fafad2 {
}

BodySystem <-- InputSystem
WeaponSystem <-- InputSystem

class Interfaces #adff2f/fafad2 {
}

Configs <-- Interfaces

class SpatialStorage #2fadff/fafad2 {
}

Environment <-- SpatialStorage

class SteeringBehaviors #2fadff/fafad2 {
}

BodySystem <-- SteeringBehaviors

class UnitSystem #2fadff/fafad2 {
}

World <-- UnitSystem

class View #2fadff/fafad2 {
}


class WeaponSystem #2fadff/fafad2 {
}


@enduml
